"""fix

Revision ID: 29de38c4d25d
Revises: cb2dfa79df20
Create Date: 2026-01-29 13:23:49.640526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29de38c4d25d'
down_revision = 'cb2dfa79df20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_point_transactions_admin_id',  # ✅ name REQUIRED
            'admins',
            ['admin_id'],
            ['id']
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
